### ISSUE TITLE
Firefox SVG sprite bug

### ISSUE THREAD

**Issue by nicolaibach** [elad2412/the-new-css-reset#11]
I noticed a strange bug in Firefox when using a SVG sprite. Some shapes render fine but others don't.

CodeSandbox: https://codesandbox.io/s/reqrh
Test Files: https://github.com/nicolaibach/svg-firefox-bug

The bug goes away if `symbol *` is excluded explicitly:

`*:where(:not(iframe, canvas, img, svg, video):not(svg *, symbol *))`

**Comment by longsonr** [comment]
Chrome now agrees with us that this is the correct rendering. I expect Safari will catch up at some point too.
