### ISSUE TITLE
a:-webkit-any-link not completely overridden

### ISSUE THREAD

**Issue by KTS915** [elad2412/the-new-css-reset#12]
The reset still leaves `text-decoration: underline` in place from the user agent stylesheet.

**Comment by elad2412** [comment]
I test it out and it look without underline.

If you mean what is written in inspect element, this is the browser that doesn't show it correctly.

[CodePen Demo](https://codepen.io/elad2412/pen/d3257e4556eb1374ec610cc3236cfe57)

Please add more information and CodePen example if I didn't understand you correctly.
