### ISSUE TITLE
Recommended combinations with normalize, sanitize, resets

### ISSUE THREAD

**Issue by hyperknot** [elad2412/the-new-css-reset#16]
I've read your articles on [Medium](https://elad.medium.com/normalize-css-or-css-reset-9d75175c5d1e) and [CSS Tricks](https://css-tricks.com/an-interview-with-elad-shechter-on-the-new-css-reset/).

Can you recommend some combinations how would you do CSS init with or without this library? How is the relationship to sanitize, they are doing similar things (border-box, etc.) aren't they? So it's either one of the other?

I guess for older browser support, the only choice is either:
- normalize + reset.local
or 
- sanitize

And for newer browsers you recommend:
- normalize + new-css-reset

Is this correct?

**Comment by elad2412** [comment]
- Sanitize is similar to normalize.css, and I don't  see the benefits of putting all the rules with the ':where()' pseudo-class.
- In old projects which I need more supports  I work with "normalize.css" and my local CSS reset.
- And for new projects I'm in the mind of normalize with my new-css-reset, it's steal taking shape and it for cutting edge web developers.

**Comment by hyperknot** [comment]
Thanks for the explanation!
