### ISSUE TITLE
CUSOR: POINTER disabled

### ISSUE THREAD

**Issue by AJamesLiptak** [elad2412/the-new-css-reset#17]
I've an issue where the following is disabling _CURSOR: POINTER_ in my custom stylesheet, even though my sheet comes _after_ the reset: 

`*:where(:not(iframe, canvas, img, svg, video):not(svg *, symbol *)) {
    * all: unset;
    display: revert;
}`

Which of the elements (canvas, img, svg) does **CURSOR: POINTER** fall?

Here are bits of the HTML . . .

       <link rel="stylesheet" href="css/css-reset_v141.css">
       <link rel="stylesheet" href="css/relearn-29nov2021.css">

              <div class="masthead toggled_element">
                   <div class="logo"><a href="#01">Fixed Header!</a></div>
                   <div id="menu_toggle" class="toggled_element menu-toggle">
                        <div class="one"></div>
                        <div class="two"></div>
                        <div class="three"></div>
                   </div>
              </div>

and my CSS.

`.menu-toggle {
    cursor: pointer;
    width: 30px;
    position: absolute;
    right: 0;
    top: 7px;
}`

**Comment by elad2412** [comment]
Please add CodePen.io example, I tried and I don't see the bug.

**Comment by AJamesLiptak** [comment]
Please take a look at my CodePen demonstrating the issue: https://codepen.io/AJamesL/pen/zYExPgo?editors=1100.

Remove/ comment out line 8 of the CSS.

`    all: unset; `

I have neither _Normalize_ or _Reset_ enabled in the Pen.
