### ISSUE TITLE
h1 still has margin-block-start / margin-block-end on chrome

### ISSUE THREAD

**Issue by Perni1984** [elad2412/the-new-css-reset#19]
Hi,

as you can see from the following pen and screenshot:
https://codepen.io/perni1984-the-sasster/pen/wvrBaBo?editors=1100
![image](https://user-images.githubusercontent.com/9039956/144116553-89c86bdd-0154-4d25-830e-cc2591c8046f.png)

The `<h1>` still has `margin-block-start` and `margin-block-end` from the browsers user agent stylesheet. Is this intended?

I would have rather expected that those styles are resetted to be 0, but maybe I am missing something.

**Comment by elad2412** [comment]
The 'all' property is resetting the margin. As you can see there is no margin, it's only the inspect element that doesn't show it in the correct way.
