### ISSUE TITLE
Would you recommend any specific way(s) of processing this for older browser support?

### ISSUE THREAD

**Issue by paulshryock** [elad2412/the-new-css-reset#2]

**Comment by eladyad2** [comment]
The main idea of this project to create a cutting-edge CSS reset.

If it is important to support older versions of browsers, it is better to use older CSS resets.

You can see my older way to reset CSS in my (old) article: "[Normalize CSS or CSS Reset?!](https://elad.medium.com/normalize-css-or-css-reset-9d75175c5d1e)"

**Comment by paulshryock** [comment]
Fair enough; thanks!
