### ISSUE TITLE
Questions regarding the main selector reset 

### ISSUE THREAD

**Issue by barak007** [elad2412/the-new-css-reset#20]
Hello I have two questions about this new cool reset. specifically this line:
https://github.com/elad2412/the-new-css-reset/blob/a46b4e46170f24825b11c1acc9b91b98234e7845/css/reset.css#L7
 
1. Can you please explain why there is a chain of `:not` instead of using single one?
  ```css
 :not(iframe, canvas, img, svg, video, svg *, symbol *)
```
2. Why there is a `*` at the beginning of the selector?

Thanks in advance.

**Comment by elad2412** [comment]
1. make semantic separations for specific elements to inner elements.
2. The "*" is for the readability of selecting all elements.

**Comment by barak007** [comment]
10x just wanted to make sure there isn't something I miss here.
