### ISSUE TITLE
make hidden attribute respected again

### ISSUE THREAD

**Issue by bitstarr** [elad2412/the-new-css-reset#21]
If an element gets a hidden attribute your current main reset is resetting it to its original display property. Can be fixed with a minor addition:
```
*:where(:not(iframe, canvas, img, svg, video, [hidden]):not(svg *, symbol *)) {
```
So the hidden attribute will force `display: none` like the browsers default behaviour.

**Comment by elektronik2k5** [comment]
This is a good idea and I'm in favor.

**Comment by elad2412** [comment]
Add this feature in a different way - updated in the last version 1.4.3

/* fix the feature of attribute hidden 
   display:revert; revert to element instead of attribute */
:where([hidden]){
    display:none;
}
