### ISSUE TITLE
Add text-size-adjust?

### ISSUE THREAD

**Issue by aaronsturm** [elad2412/the-new-css-reset#32]
Hello!

I came across [this article today on text-size-adjust](https://css-tricks.com/your-css-reset-needs-text-size-adjust-probably/) and am wondering if it's worth setting it to `none` in the reset? Reading the MDN article, I'm not sure if `unset` does the same thing.

**Comment by QINGCHARLES** [comment]
Agree. After reading all the documentation it probably should be included.

**Comment by aradalvand** [comment]
This needs to be added: https://kilianvalkhof.com/2022/css-html/your-css-reset-needs-text-size-adjust-probably/

**Comment by fabulousgk** [comment]
Saddly, I dont think Elad is really maintaining this anymore.  Seems to be the thing with resets, they die from lack of maintance.

**Comment by elektronik2k5** [comment]
I'm in favor. @elad2412 ?

**Comment by elad2412** [comment]
@aaronsturm,  @fabulousgk, @QINGCHARLES  & @elektronik2k5 release a new version with this treatment.

Issue Closed :-)
