### ISSUE TITLE
Minimize use of revert

### ISSUE THREAD

**Issue by Justin-Marks** [elad2412/the-new-css-reset#38]
Since the point is to eliminate browser inconsistencies by not using the browser's default styles, in principle it should be better to not use revert (whose value can differ depending on browser) unless needed. For instance,

```
a, button {
    /* cursor: revert; */ 
    cursor: pointer;
}
```

**Comment by elad2412** [comment]
Hi @Justin-Marks, 
Is there a browser that works differently in this case?

**Comment by Justin-Marks** [comment]
I don't know, but this is exactly the problem: how can you be sure there are no inconsistencies? Even if you test every browser and find no inconsistencies, it's always possible that a future browser will work differently. By using revert it opens the _possibility_ of differences occurring, and creates a sense of uncertainty for the developer.

**Comment by Justin-Marks** [comment]
I don't know, but this is exactly the problem with revert: how can you be sure there are no inconsistencies? Even if you test every browser and find no inconsistencies, it's always possible that a future browser will work differently. By using revert it opens the _possibility_ of differences occurring, which creates a sense of uncertainty for the developer.

**Comment by elad2412** [comment]
The use in this is particular, and there is no good reason not to use it here.

**Comment by Justin-Marks** [comment]
I believe you've missed the point, this issue is not about that particular case per se. The point is revert relies on the user agent stylesheet which opens the possibility for inconsistencies.

Compare (current):

```
a, button {
    cursor: revert;
}

textarea {
    white-space: revert;
}

```
To:

```
a, button {
    cursor: pointer;
}

textarea {
    white-space: pre-wrap;
}
```

The latter style is superior for 2 reasons:

1) Even if these work the same in practice, with revert it's impossible to know _a priori_ whether inconsistencies exist. You'd have to assume based on testing, trust, or from personal experience. Besides the possibility of being wrong, the assumption is not completely reliable because a future browser's styles could be inconsistent with the current ones (it's always possible, even if unlikely). In the latter style you'd know exactly what value to expect _a priori_, and with absolute certainty.

2) If these don't work the same in practice, meaning there's an inconsistency among browsers for these properties, then the latter style would serve to normalize that inconsistency. The former style with revert would not, which compared to the latter style doesn't fit well with the purpose of a reset.

For these reasons, the latter style should be preferable and revert should generally be avoided (unless impossible or unfeasible to do so).

**Comment by twofivetwo** [comment]
`a, button {
    cursor: revert;
}`

in the case of buttons in Firefox Dev, Chromium and Chrome revert does not work.

**Comment by jeffnyman** [comment]
For what it's worth, I entirely agree with the above comment. Using a vague qualifier like "revert" is basically saying "something will happen here that is based on the context at the time." In this case, "context at the time" will be the state of any given browser at that time.

In software development, we would call this a vague requirement. The lack of specificity of intent is exactly why you would probably want to avoid this.

I guess the question (which was never answered, much less discussed) is: why put so much trust in revert? Why not just be specific if you are overriding something that was unset?

**Comment by TRexStark** [comment]
the revert value in this instance does not work in Chrome for buttons specifically / meaning the button's cursor does not become "pointer" ... therefore you will have to set the pointer value for it to work. Not sure about other browsers, but this is the only case I've seen

**Comment by graymatter00** [comment]
> the revert value in this instance does not work in Chrome for buttons specifically / meaning the button's cursor does not become "pointer" ... therefore you will have to set the pointer value for it to work. Not sure about other browsers, but this is the only case I've seen

The default or expected cursor for a button is not "pointer".  See https://ux.stackexchange.com/questions/3788/default-cursor-on-mouse-over-of-a-button-is-not-a-hand-pointer.  This means that, even when not using the-new-css-reset, one must apply `cursor: pointer` to buttons if the pointer (hand) cursor is required.

**Comment by TRexStark** [comment]
Thanks @graymatter00 - I must admit, I didn't know that - I thought only the input with type button, submit etc... would not have pointer by default. _"Everyday you learn something new"_
