### ISSUE TITLE
all: unset isn't hyphens-friendly

### ISSUE THREAD

**Issue by raphaelgoetter** [elad2412/the-new-css-reset#41]
Hello,

It seems that `all: unset` disallows `hyphens` property on elements (or another property which goes along with `hyphens`)

See : https://codepen.io/raphaelgoetter/pen/ZErGoae (uncomment `all: unset` to enable `hyphens: auto`)

**Comment by elad2412** [comment]
You are using an old version. 

The new version 1.6.0 is fixing this issue.
