### ISSUE TITLE
Any plans to output css in JavaScript object notation syntax?

### ISSUE THREAD

**Issue by Brisklemonade** [elad2412/the-new-css-reset#42]
I myself am a creator of a library, and would love to update my normalize css to use this. However, my library uses css-in-js, so I won't be able to use it in its current state.

Will there be any plans to release a JS object syntax version of this css reset?

**Comment by elektronik2k5** [comment]
@Brisklemonade you can read the file and inline it as part of your build stage. There are appropriate tools for this kind of setup. In webpack, for example, you can use the `raw-loader` for this purpose (v4) or the modern equivalent https://webpack.js.org/guides/asset-modules/#inlining-assets in v5.

**Comment by elad2412** [comment]
Hi @Brisklemonade, see if @elektronik2k5 is answering your question
