### ISSUE TITLE
Browser error message regarding -webkit-line-break

### ISSUE THREAD

**Issue by HummingMind** [elad2412/the-new-css-reset#46]
Hello,
I am getting this in edge 102 (marked as an error):

![image](https://user-images.githubusercontent.com/87399963/175173305-6360dc2e-d3ae-455b-9d56-e3a2fea7cf76.png)

Does the regular "line-break" need to be added?

Thank you.

**Comment by elad2412** [comment]
The test is to see that texteditable attribute is responding. 

You can see that are several definitions in order to support all browsers.

I tested texteditable attribute on Edge and it works fine. 

Issue closed

**Comment by ifohancroft** [comment]
I would argue that this is a bug in Edge causing it to not ignore engine prefixes that don't apply to it.
