### ISSUE TITLE
Use logical properties

### ISSUE THREAD

**Issue by winston0410** [elad2412/the-new-css-reset#47]
REF: https://web.dev/learn/design/responsive-images/#constrain-your-images

I am still trying to digest that, but basically we need to use this:

```css
img {
  max-inline-size: 100%;
}
```

instead of this(which is what this library is providing right now), to accommodate other writing modes

https://github.com/elad2412/the-new-css-reset/blob/f6bfae6355b70dabdb5e81c8b90915249c9104d7/css/reset.css#L33-L35

**Comment by elad2412** [comment]
Took me a lot of time to think about this, I change to Logical Properties and add the "max-height:100%" as well.

No matter what the image should noe exceed the width and the height from a definied container, unless the user is definding it.

The code that updated (version 1.8.2):
```
/* For images to not be able to exceed their container */
img {
    max-inline-size: 100%;
    max-block-size: 100%;
}
```
