### ISSUE TITLE
First line causing problemas with flip cards in Safari

### ISSUE THREAD

**Issue by mfagundesleal** [elad2412/the-new-css-reset#48]
Problems with flip cards in Safari.
After removing the line below, the backface is hidden again, solving the problem. With it applied, even using the -webkit- prefix, the backface was mirrored. I currently use SASS, but even with vanilla CSS the problems occurs.
```
*:where(:not(html, iframe, canvas, img, svg, video):not(svg *, symbol *))
    all: unset
    display: revert
```
I also use version 8.0.1 of normalize.css, but in the tests I performed the behavior remained unchanged even with its removal.

**Comment by elad2412** [comment]
Hi @mfagundesleal , 
Please provide CodePen with the issue.

**Comment by elad2412** [comment]
This issue closed because: no demo was provided.
