### ISSUE TITLE
Remove list-style on `summary`

### ISSUE THREAD

**Issue by idesmar** [elad2412/the-new-css-reset#52]
`summary` has list style that needs to be removed.

![summary_list_style](https://user-images.githubusercontent.com/77437226/191588122-187b2f5f-369b-493b-b39e-aa649c0d22e0.png)
https://codepen.io/idesmar/pen/JjvyJRa?editors=1000

**Comment by elad2412** [comment]
Added patch for new version 1.8.1

```
/* remove default dot (•) sign */
::marker {
    content: "";
}
```
