### ISSUE TITLE
:: marker { content: ""; } prevents list-styling

### ISSUE THREAD

**Issue by birkheadc** [elad2412/the-new-css-reset#59]
The following code from lines 69-72:

```
/* remove default dot (•) sign */
/* ::marker {
  content: "";
} */
```

overrides list-style on all ul and ol elements, preventing the use of list-styling entirely.

This can be fixed by the user by resetting ::marker via `::marker { content: initial }` for the li in question, but some users might not be accustomed to using ::marker to style their lists, and so might not realize what is going wrong. (It's me. I am 'some users'.)

If this is intended, maybe the comment on this section could be updated for clarity.

**Comment by elad2412** [comment]
Yes, this is correct in the case of this CSS Reset. Updated in the new version 1.8.3

Thanks for the follow-up :-)
