### ISSUE TITLE
Resets H1 style to body style

### ISSUE THREAD

**Issue by dy** [elad2412/the-new-css-reset#6]
`<main><h1>Hello World</h1></main>` displays as body text. Isn't a bit too hard?

**Comment by elad2412** [comment]
The main idea of CSS reset is different from normalize.CSS project is to use your own style without the default declaration of the browsers.

In most cases when you denied H elements you want to declare your own styles, like font-size, font-weight, and margin.

Not anyone like CSS reset, and for those web developer maybe it's better to use Normalize.css.
