### ISSUE TITLE
<input type="color"> display problem

### ISSUE THREAD

**Issue by lymnee** [elad2412/the-new-css-reset#61]
```
    <p>
      <label for="example-input-color">Color</label>
      <input type="color" id="example-input-color" placeholder="#fff">
    </p>
```
A display problem occurs with the Google Chrome browser (version 109.5414.74..0.5414.74): a long left border appears, using only The new CSS reset.

Thanks.

**Comment by graymatter00** [comment]
@lymnee The issue you raise is discussed here [https://github.com/elad2412/the-new-css-reset/pull/7](https://github.com/elad2412/the-new-css-reset/pull/7).  This comment [https://github.com/elad2412/the-new-css-reset/pull/7#issuecomment-885346620](https://github.com/elad2412/the-new-css-reset/pull/7#issuecomment-885346620) suggests that adding the correct Doctype fixes the issue.

**Comment by lymnee** [comment]
> @lymnee The issue you raise is discussed here #7. This comment [#7 (comment)](https://github.com/elad2412/the-new-css-reset/pull/7#issuecomment-885346620) suggests that adding the correct Doctype fixes the issue.

 Thank you for pointing me in the right direction. The bug was from comments placed before '<!DOCTYPE html>'. It's valid, but not for Google Chrome.
