### ISSUE TITLE
Issue with specificity?

### ISSUE THREAD

**Issue by felixsanz** [elad2412/the-new-css-reset#62]
This code: 

```
*:where(:not(html, iframe, canvas, img, svg, video, audio):not(svg *, symbol *)) {
    all: unset;
    display: revert;
}
```

is not only doing `Remove all the styles of the "User-Agent-Stylesheet", except for the 'display' property`.

Because specificity is so high you can't set, for example, `word-spacing` on `body`. Not even `html body` beats it. So what are the options? Isn't this an issue?

**Comment by felixsanz** [comment]
mmm... i think it works fine but devtools messes up. It crosses my rules and it's saying that this `all: unset` takes precedence, even if looks like not. It's just me?

**Comment by graymatter00** [comment]
Can you provide an example.  Perhaps on [CodePen](https://codepen.io/).

**Comment by felixsanz** [comment]
Can't reproduce it on isolation, so maybe an issue on how an issue with vite, the framework, etc.

Closing!
