### ISSUE TITLE
Why reset inline elements <b> and <strong> to blocks?

### ISSUE THREAD

**Issue by adi518** [elad2412/the-new-css-reset#74]
Seems unintuitive.

**Comment by fabulousgk** [comment]
I do not see any indication of this.

**Comment by adi518** [comment]
It ended up not bothering, but I did notice the computed CSS property is showing `block`, so it could still be an issue at some point.

**Comment by fabulousgk** [comment]
I just check in Firefox and Chrome and display is set to inline in the computed changes with only this reset applied.

**Comment by adi518** [comment]
Will check again. Are you sure it doesn't point to the reset's `revert` prop?

**Comment by fabulousgk** [comment]
Even when I deselect that it is still inline.  display: revert is to fix the block level elements that get set to inline by the main reset
