### ISSUE TITLE
Doesn't remove body's margin

### ISSUE THREAD

**Issue by php4fan** [elad2412/the-new-css-reset#84]
The body still has the annoying default 8px margin.

That's like the number 1 or 2 thing that I would expect a reset stylesheet to reset.

**Comment by fabulousgk** [comment]
It most certainly does reset it, not only the body but all margins.
## With reset
<img width="1036" alt="Screen Shot 2024-03-15 at 12 18 09 PM" src="https://github.com/elad2412/the-new-css-reset/assets/126961361/cd6e692a-86d7-4225-8c33-323435c45534">

## With reset unchecked
<img width="1034" alt="Screen Shot 2024-03-15 at 12 18 37 PM" src="https://github.com/elad2412/the-new-css-reset/assets/126961361/c67f9a2c-11cd-4107-8ce4-637b76523615">

**Comment by php4fan** [comment]
Hmmm, it seems Chrome's devtools are showing inconsistent information, and I blindly trusted it.

Sorry.
