### ISSUE TITLE
Problems with hyphens

### ISSUE THREAD

**Issue by bitstarr** [elad2412/the-new-css-reset#86]
In Chrome (and derived browsers like Edge) the property `all: unset` kills the ability to hyphenate text.

Even after setting all hyphens related properties, you cannot get any hyphenation.

```
    hyphens: auto;
    hyphenate-character: '-';
    hyphenate-limit-chars: 10 4 4;
```

I was working happily with most parts of this reset, but now I have to adjust around this issue.

**Comment by fabulousgk** [comment]
Can you confirm what version of the reset you are using?

Does this line, exactly match, specifically the html element?
`*:where(:not(html, iframe, canvas, img, svg, video, audio):not(svg *, symbol *)) {`

**Comment by bitstarr** [comment]
ah I see, you added html to the exlusion list.

i was using `:where( :not( iframe, canvas, img, svg, video ):not( svg *, symbol * ) ) {`

**Comment by elad2412** [comment]
Sorry for the late answer. From what I see I can close this issue. If anything is still an issue please let me know.
