### ISSUE TITLE
Causes checkboxes to disappear.

### ISSUE THREAD

**Issue by Alcapwn1** [elad2412/the-new-css-reset#90]
[Codepen with issue displayed](https://codepen.io/CIMSIO/pen/pomadGG)

**Comment by fabulousgk** [comment]
This is intended.  This reset is very aggressive and requires a dev to apply their own styling to all elements.

**Comment by Alcapwn1** [comment]
> This is intended. This reset is very aggressive and requires a dev to apply their own styling to all elements.

Thank you!
